### ISSUE TITLE
Should migrate some of the tools at bitaddress.org

### ISSUE THREAD

**Issue by Transisto** [BitcoinQnA/seedtool#34]
https://github.com/pointbiz/bitaddress.org

One thing I like is having the mouse movement and keyboard change the entropy. I don't know how seedtool currently does when it's "Calculating" but I would trust it more if it included some user inputs.

Also some version of a Brain wallet that accept any string of character as entropy (at your own risk!) and generate an xpriv instead of a single address would be amazing.

**Comment by SuperPhatArrow** [comment]
Hi @Transisto 

The internet has come a long way since 2012 and all modern browsers have [a cryptographically strong pseudo-random number generator seeded with truly random values](https://w3c.github.io/webcrypto/#crypto-interface) 

If you want to move your mouse around, I'm not sure if it affects what is in `/dev/urandom` but perhaps it does in some operating systems and perhaps some browsers' implementation of the [Web Crypto API](https://developer.mozilla.org/en-US/docs/Web/API/Web_Crypto_API). If I made a user interface that "affected entropy" by moving a mouse or clicking a keyboard, I would just be faking it. There is no need to do this anymore as all modern browsers can provide you with very good quality entropy.

> Also some version of a Brain wallet that accept any string of character as entropy (at your own risk!) and generate an xpriv instead of a single address would be amazing.

Seed tool does currently do this and has since first release.

1. Open "Seed Generation/Input" Section
2. Click on 🎲 to input your own entropy, there a number of types of input for you to choose. Mashing your keyboard is not one of them as that is not really entropy.
3. Input your own entropy into the box provided (at your own risk!)
4. Once you have sufficient entropy, the `xpriv` will appear in the box with the label "BIP32 Root Key"
